apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ww38
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0032-tenant/tkrw-pr712-0075-0032-app/devfile-sample-ww38@sha256:b77a2a15ce98f17af01206c10297b1dcb2dc68a3e81ed9f5ffec9b9098f2adab
        name: my-nodejs
        resources: {}
status: {}
